services:
  mysql:
    image: mysql:8.0.39
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - ${DB_PORT}:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
