name: Development CI/CD

on:
  workflow_dispatch:
  push:
    branches: ['dev']

jobs:
  deploy-dev:
    uses: ./.github/workflows/reusable.yml
    with:
      environment: 'dev'
      runner-label: 'develop'
