name: Production CI/CD

on:
  workflow_dispatch:

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Cache npm dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

  checkout:
    needs: test
    runs-on: [self-hosted, production]
    environment: prod
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

  build:
    needs: checkout
    name: Build Node app
    uses: ./.github/workflows/build-node-app.yml
    with:
      environment: prod
      runner: production

  deploy-prod:
    needs: build
    name: Deploy to development environment
    uses: ./.github/workflows/deploy.yml
    with:
      environment: prod
      runner: production
    secrets:
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_NAME: ${{ secrets.DB_NAME }}
      AUTH_SECRET: ${{ secrets.AUTH_SECRET }}