name: Pull Request CI

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    name: Build Node app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: 'npm'
      - name: Install dependencies
        run: npm i
      - name: Build application
        run: npm run build
      - name: Run tests
        run: npm run test
